version: "3.8"
services:
  server:
    image: airy-backend:latest
    build: .
    container_name: airy-server
    restart: always
    ports:
    - target: 8081
      published: 8081
    networks:
      - airy-net
    depends_on:
      - postgres
    environment:
      - BROKER_ADDRESS=${BROKER_ADDRESS}
      - POSTGRES_ADDRESS=${POSTGRES_ADDRESS}
    command: ["/server"]
  processor:
    image: airy-backend:latest
    build: .
    container_name: airy-processor
    restart: always
    networks:
      - airy-net
    depends_on:
      - mosquitto
      - postgres
    environment:
      - BROKER_ADDRESS=${BROKER_ADDRESS}
      - POSTGRES_ADDRESS=${POSTGRES_ADDRESS}
    command: ["/processor"]
