version: "3.8"
services:
  server:
    container_name: airy-server
    restart: always
    ports:
    - target: 8081
      published: 8081
    build: 
      dockerfile: server.dockerfile
    networks:
      - airy-net
    depends_on:
      - postgres
    environment:
      - BROKER_ADDRESS=${BROKER_ADDRESS}
      - POSTGRES_ADDRESS=${POSTGRES_ADDRESS}
  processor:
    container_name: airy-processor
    restart: always
    build: 
      dockerfile: processor.dockerfile
    networks:
      - airy-net
    depends_on:
      - mosquitto
      - postgres
    environment:
      - BROKER_ADDRESS=${BROKER_ADDRESS}
      - POSTGRES_ADDRESS=${POSTGRES_ADDRESS}
