version: "3.8"
services:
  mosquitto:
    ports:
      - target: 8883
        published: 8883
        protocol: tcp
        mode: host
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host

  server:
    restart: always
    ports:
    - target: 8081
      published: 8081
    build: server/.
    networks:
      - tatadata-net
    depends_on:
      - mosquitto
      - postgres
networks:
  tatadata-net:
    external: false
