version: "3.8"
services:
  mosquitto:
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
        
  postgres:
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
networks:
  tatadata-net:
    external: false
