version: "3.8"
services:
  postgres:
    image: postgres
    container_name: airy-postgres
    networks:
      - airy-net
    restart: always
    environment:
      POSTGRES_PASSWORD: tatadata
      POSTGRES_USER: tatadata
      POSTGRES_DB: tatadata
    volumes:
      - type: bind
        source: ./__binds/postgresql/data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./__binds/postgresql/docker-entrypoint-initdb.d
        target: /docker-entrypoint-initdb.d
  mosquitto:
    container_name: airy-mosquitto
    restart: always
    image: eclipse-mosquitto
    networks:
      - airy-net
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./__binds/mosquitto/config
        target: /mosquitto/config
        read_only: true
networks:
  airy-net:
    external: false
